language: cpp
compiler: gcc

before_install:
  - ORG_PATH=`pwd`
  - echo $LANG
  - echo $LC_ALL

  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  # cmake
  - sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12

  - sudo apt-get update -qq

  # cmake update
  - sudo apt-get install 'cmake-data'
  - sudo apt-get install 'cmake'

  # gtest https://github.com/travis-ci/travis-ci/issues/1294
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"


install:
  # g++4.8.1
  - sudo apt-get install -qq g++-4.8
  # - export CXX="g++-4.8"
  - sudo apt-get install 'libboost1.55-dev' 'libboost-date-time1.55-dev' 'libboost-graph1.55-dev' 'libboost-system1.55-dev' 'libboost-filesystem1.55-dev' 'libmsgpack-dev'

  # glog
  - mkdir -p temp/src/google-glog
  - cd temp/src/google-glog
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - tar xvzf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - ./configure
  - make
  - sudo make install
  - cd $ORG_PATH

  # gflags
  - mkdir -p temp/src/google-gflags
  - cd temp/src/google-gflags
  - wget https://codeload.github.com/gflags/gflags/zip/master
  - unzip master
  - cd gflags-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd $ORG_PATH

  # gmock
  - mkdir -p temp/src/google-gmock
  - cd temp/src/google-gmock
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - cd gmock-1.7.0
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo cp libgmock.a /usr/local/lib
  # - sudo make install
  - cd $ORG_PATH

script: make
os: linux

notifications:
  email:
    - naya@val.co.jp

